"use client"

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../app/globals.css";
import { useState } from "react";
import { SignedIn, SignedOut, SignInButton, SignUpButton, UserButton } from "@clerk/nextjs";
import Link from "next/link";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function NavMenu() {
    const [menuOpen, setMenuOpen] = useState(false);

    return (
        <nav className="ml-auto">
            {/* Desktop menu */}
            <ul className="hidden md:flex gap-6 items-center">
                <SignedOut>
                    <>
                        <li>
                            <SignInButton mode="modal">
                                <div className="flex items-center gap-1 text-gray-800 dark:text-gray-100 hover:underline cursor-pointer">
                                    {/* User icon */}
                                    <svg className="w-5 h-5 text-blue-500" fill="currentColor" viewBox="0 0 20 20">
                                        <path d="M10 10a4 4 0 100-8 4 4 0 000 8zm-7 8a7 7 0 1114 0H3z" />
                                    </svg>
                                    Login
                                </div>
                            </SignInButton>
                        </li>
                        <li>
                            <SignUpButton mode="modal">
                                <div className="flex items-center gap-1 text-gray-800 dark:text-gray-100 hover:underline cursor-pointer">
                                    {/* Pencil icon */}
                                    <svg className="w-5 h-5 text-pink-500" fill="currentColor" viewBox="0 0 20 20">
                                        <path d="M17.414 2.586a2 2 0 00-2.828 0l-9.9 9.9a1 1 0 00-.263.465l-1.414 5.657a1 1 0 001.213 1.213l5.657-1.414a1 1 0 00.465-.263l9.9-9.9a2 2 0 000-2.828l-2.83-2.83zM15 7l-2-2 2-2 2 2-2 2z" />
                                    </svg>
                                    Register
                                </div>
                            </SignUpButton>
                        </li>
                    </>
                </SignedOut>
                <SignedIn>
                    <>
                        <li>
                            <a
                                href="https://meet.google.com/new"
                                target="_blank"
                                rel="noopener noreferrer"
                                className="inline-flex items-center hover:underline transition"
                            >
                                <svg
                                    className="w-5 h-5 mr-2"
                                    fill="currentColor"
                                    viewBox="0 0 20 20"
                                    xmlns="http://www.w3.org/2000/svg"
                                >
                                    <path d="M15 8l4-4v12l-4-4v4H3V4h12v4z" />
                                </svg>

                                Start a Google Meet
                            </a>
                        </li>
                        <li>
                            <UserButton />
                        </li>
                    </>
                </SignedIn>
            </ul>
            {/* Mobile menu button */}
            <button
                className="md:hidden ml-2 p-2 rounded hover:bg-gray-200 dark:hover:bg-gray-800"
                onClick={() => setMenuOpen(!menuOpen)}
                aria-label="Open menu"
            >
                <svg className="w-6 h-6 text-gray-800 dark:text-gray-100" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M4 6h16M4 12h16M4 18h16" />
                </svg>
            </button>
            {/* Mobile dropdown */}
            {menuOpen && (
                <ul className="absolute right-6 top-16 bg-white dark:bg-gray-900 shadow rounded-md flex flex-col gap-2 p-4 md:hidden z-50">
                    <SignedOut>
                        <>
                            <li>
                                <a href="/login" className="flex items-center gap-1 text-gray-800 dark:text-gray-100 hover:underline">
                                    <svg className="w-5 h-5 text-blue-500" fill="currentColor" viewBox="0 0 20 20">
                                        <path d="M10 10a4 4 0 100-8 4 4 0 000 8zm-7 8a7 7 0 1114 0H3z" />
                                    </svg>
                                    Login
                                </a>
                            </li>
                            <li>
                                <a href="/register" className="flex items-center gap-1 text-gray-800 dark:text-gray-100 hover:underline">
                                    <svg className="w-5 h-5 text-pink-500" fill="currentColor" viewBox="0 0 20 20">
                                        <path d="M17.414 2.586a2 2 0 00-2.828 0l-9.9 9.9a1 1 0 00-.263.465l-1.414 5.657a1 1 0 001.213 1.213l5.657-1.414a1 1 0 00.465-.263l9.9-9.9a2 2 0 000-2.828l-2.83-2.83zM15 7l-2-2 2-2 2 2-2 2z" />
                                    </svg>
                                    Register
                                </a>
                            </li>
                        </>
                    </SignedOut>
                    <SignedIn>
                        <>
                            <li>
                                <a href="/meet/new" className="flex items-center gap-1 text-gray-800 dark:text-gray-100 hover:underline">
                                    <svg className="w-5 h-5 text-green-500" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                                        <rect x="3" y="4" width="18" height="18" rx="2" fill="none" stroke="currentColor" />
                                        <path d="M16 2v4M8 2v4M3 10h18" stroke="currentColor" />
                                    </svg>
                                    Create a new meet
                                </a>
                            </li>
                            <li>
                                <button className="flex items-center gap-1 text-gray-800 dark:text-gray-100 hover:underline">
                                    <svg className="w-5 h-5 text-red-500" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                                        <path d="M17 16l4-4m0 0l-4-4m4 4H7" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" />
                                        <path d="M3 21V3a2 2 0 012-2h7" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" />
                                    </svg>
                                    Logout
                                </button>
                            </li>
                        </>
                    </SignedIn>
                </ul>
            )}
        </nav>
    );
}